[window]

dimensions = { columns = 100, lines = 28}

decorations = "Full"

opacity = 1.0

startup_mode = "Windowed"

title = "Terminal"

dynamic_title = true

[scrolling]

history = 100000

[font]

normal = { family = "Maple Mono Normal NL NF", style = "Regular" }
bold = { family = "Maple Mono Normal NL NF", style = "Bold" }
italic = { family = "Maple Mono Normal NL NF", style = "Italic" }
bold_italic = { family = "Maple Mono Normal NL NF", style = "Bold Italic" }
size = 15.0

[cursor]

style = { shape = "Block", blinking = "On"}

thickness = 0.15

[terminal]

shell = { program = "/bin/zsh" }
# shell = "{ program = "/bin/bash" },
